name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  checkov:
    name: Checkov - IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@v11
        with:
          directory: .
          skip-check: CKV_DOCKER_2,CKV_GITHUB_1

  bandit:
    name: Bandit - Security Linter for Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install bandit
      - name: Run Bandit scan
        run: bandit -r backend

  trivy:
    name: Trivy - Container Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'filesystem'
          vuln-type: 'os,library'
          path: '.'

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          source venv/bin/activate || python -m venv venv && source venv/bin/activate
          pip install -r requirements.txt
          pytest backend/tests || true
